# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='location',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='student',
        ),
        migrations.AddField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.ManyToManyField(to='student_app.Exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.ManyToManyField(to='student_app.Subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
