# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_auto_20170814_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student',
            new_name='exam',
        ),
    ]
