# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_auto_20170814_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='exam_type',
            new_name='exam_title',
        ),
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
