# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_auto_20170814_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_title',
            field=models.CharField(blank=True, choices=[('1', 'Quarterly'), ('2', 'Half_yearly'), ('3', 'Annualy')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, choices=[('1', 'Maths'), ('2', 'Physics'), ('3', 'Chemistry'), ('4', 'Hindi'), ('5', 'English')], max_length=150, null=True),
        ),
    ]
