# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_auto_20170814_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='no_of_classes',
        ),
    ]
