# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0007_remove_exam_roll_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='total_marks',
            new_name='exam_marks',
        ),
        migrations.AddField(
            model_name='student',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
