# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0008_auto_20170814_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='section',
        ),
        migrations.AddField(
            model_name='section',
            name='class_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_app.Class'),
        ),
    ]
