# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0010_auto_20170814_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_marks',
            field=models.IntegerField(default=0),
        ),
    ]
